### ISSUE TITLE
Scrolling text for display names

### ISSUE THREAD

**Issue by linux-lukas** [defnull/fediwall#8]
Longer display names will be cut off - here a scrolling text would be better, so that the name can be displayed completely.

Example: https://jugendforum-nrw.de/fediwall: 

![image](https://github.com/defnull/fediwall/assets/47597136/f81dcfc1-d05a-48a8-bd5b-e851d81167f2)

**Comment by defnull** [comment]
I think there is a CSS-only solution to this. Something like:

```css
.animoverflow {
    width: 300px;
    background-color: black;
    white-space: nowrap;
    overflow: hidden;
    box-sizing: border-box;
}

.animoverflow > * {
  display: inline-block;
  position: relative;
  color: #FFF;
  padding: 0 1em;
  animation-name: autoscroll;
  animation-duration: 5s;
  animation-timing-function: ease-in-out;
  animation-iteration-count: infinite;
  animation-direction: alternate;
}

@keyframes autoscroll {
  0%, 50% {
    transform: translateX(0%);
    left: 0%;
  }
  100% {
    transform: translateX(-100%);
    left: 100%;
  }
}
```
